sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t babu08/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true babu08/docker-react npm run test

